# Generated by Django 4.2.19 on 2025-03-05 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='title',
            new_name='movie_title',
        ),
    ]
